# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-Monster
version:      1.01
version_from: lib/WWW/Search/Monster.pm
installdirs:  site
requires:
    HTML::TreeBuilder:             0
    WWW::Search:                   0
    WWW::Search::Result:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
